# Generated by Django 5.1.7 on 2025-04-25 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectvault', '0003_rename_projects_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
