# Generated by Django 5.1.7 on 2025-04-25 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectvault', '0004_project_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
