# Generated by Django 5.1.7 on 2025-04-27 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectvault', '0006_project_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='static/assets/images')),
            ],
        ),
        migrations.RemoveField(
            model_name='project',
            name='image',
        ),
        migrations.RemoveField(
            model_name='projectcontent',
            name='image',
        ),
        migrations.AddField(
            model_name='project',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='projects', to='projectvault.image'),
        ),
        migrations.AddField(
            model_name='projectcontent',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='content_blocks', to='projectvault.image'),
        ),
    ]
