# Generated by Django 5.1.7 on 2025-04-27 21:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectvault', '0007_image_remove_project_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_images', to='projectvault.project'),
        ),
        migrations.AddField(
            model_name='image',
            name='project_content',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='content_images', to='projectvault.projectcontent'),
        ),
    ]
