# Generated by Django 5.1.7 on 2025-04-27 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectvault', '0008_image_project_image_project_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectcontent',
            name='images',
        ),
        migrations.RemoveField(
            model_name='project',
            name='images',
        ),
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/assets/images'),
        ),
        migrations.AddField(
            model_name='projectcontent',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/assets/images'),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
