# Generated by Django 5.1.7 on 2025-04-27 22:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectvault', '0009_remove_projectcontent_images_remove_project_images_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectcontent',
            old_name='image',
            new_name='images',
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='static/assets/images')),
                ('project_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_images', to='projectvault.projectcontent')),
            ],
        ),
    ]
