# Generated by Django 5.1.7 on 2025-04-27 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectvault', '0010_rename_image_projectcontent_images_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectcontent',
            name='images',
        ),
        migrations.AddField(
            model_name='projectcontent',
            name='images',
            field=models.ManyToManyField(blank=True, to='projectvault.images'),
        ),
    ]
