# Generated by Django 5.1.7 on 2025-04-27 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectvault', '0011_remove_projectcontent_images_projectcontent_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectcontent',
            name='images',
        ),
        migrations.DeleteModel(
            name='Images',
        ),
        migrations.AddField(
            model_name='projectcontent',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='static/assets/images'),
        ),
    ]
