# Generated by Django 5.1.7 on 2025-04-28 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectvault', '0012_remove_projectcontent_images_delete_images_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectcontent',
            name='code',
            field=models.TextField(blank=True),
        ),
    ]
