# Generated by Django 5.1.7 on 2025-04-28 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectvault', '0014_projectimages'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProjectImages',
            new_name='ProjectImage',
        ),
    ]
